export const GOAL_MESSAGE_TYPE_GOAL_SET = "GOAL_SET";
export const GOAL_MESSAGE_TYPE_PROOF_POSTED = "PROOF_POSTED";
export const GOAL_MESSAGE_TYPE_MESSAGE_POSTED = "MESSAGE_POSTED";
export const GOAL_MESSAGE_TYPE_GOAL_CLOSED_AS_ACHIEVED =
  "GOAL_CLOSED_AS_ACHIEVED";
export const GOAL_MESSAGE_TYPE_GOAL_CLOSED_AS_FAILED = "GOAL_CLOSED_AS_FAILED";
