export const GOAL_STEP_TYPE_GOAL_IS_SET = "GOAL_IS_SET";
export const GOAL_STEP_TYPE_MOTIVATOR_IS_ADDED = "MOTIVATOR_IS_ADDED";
export const GOAL_STEP_TYPE_MOTIVATOR_IS_ACCEPTED = "MOTIVATOR_IS_ACCEPTED";
export const GOAL_STEP_TYPE_GOAL_CLOSED_AS_ACHIEVED = "GOAL_CLOSED_AS_ACHIEVED";
export const GOAL_STEP_TYPE_GOAL_CLOSED_AS_FAILED = "GOAL_CLOSED_AS_FAILED";
