export const GOAL_STEP_TYPE_GOAL_SET = "GOAL_SET";
export const GOAL_STEP_TYPE_MOTIVATOR_ADDED = "MOTIVATOR_ADDED";
export const GOAL_STEP_TYPE_MOTIVATOR_ACCEPTED = "MOTIVATOR_ACCEPTED";
export const GOAL_STEP_TYPE_MESSAGE_POSTED = "MESSAGE_POSTED";
export const GOAL_STEP_TYPE_VERIFICATION_DATA_SET = "VERIFICATION_DATA_SET";
export const GOAL_STEP_TYPE_GOAL_VERIFIED_AS_ACHIEVED =
  "GOAL_VERIFIED_AS_ACHIEVED";
export const GOAL_STEP_TYPE_GOAL_VERIFIED_AS_FAILED = "GOAL_VERIFIED_AS_FAILED";
export const GOAL_STEP_TYPE_GOAL_VERIFIED_AS_NOT_ACHIEVED_YET =
  "GOAL_VERIFIED_AS_NOT_ACHIEVED_YET";
export const GOAL_STEP_TYPE_GOAL_CLOSED_AS_ACHIEVED = "GOAL_CLOSED_AS_ACHIEVED";
export const GOAL_STEP_TYPE_GOAL_CLOSED_AS_FAILED = "GOAL_CLOSED_AS_FAILED";
